// components/Header.vue
<template>
  <header class="header">
    <Container>
      <nav>
        <n-link class="header-brand" to="/">
          Vinicius Vicentini
        </n-link>

        <div class="header-actions">
          <!-- <n-link to="/buscar" prefetch>
            <SearchIcon />
          </n-link> -->
          <ColorMode />
        </div>
      </nav>
    </Container>
  </header>
</template>

<script>
// import { SearchIcon } from 'vue-feather-icons'

export default {
  components: {
    Container: () => import('@/components/Container'),
    ColorMode: () => import('@/components/ColorMode'),
    // SearchIcon,
  },
}
</script>

<style lang="scss" scoped>
.header {
  position: sticky;
  top: 0;
  z-index: 1020;
  height: 60px;
  margin-bottom: 48px;
  background-color: rgba(15, 15, 15, 0.9);

  nav {
    display: flex;
    align-items: center;
    justify-content: space-between;
    height: 100%;
  }

  &-brand {
    font-size: 16px;
    font-style: italic;
    font-weight: 300;
    color: #fff;

    @include md {
      font-size: 25px;
    }

    &::before,
    &::after {
      font-weight: 400;
    }

    &::before {
      content: '<';
    }

    &::after {
      content: ' />';
    }
  }

  &-actions {
    display: flex;
    align-items: center;

    :not(:last-child) {
      margin-right: 20px;
    }
  }
}
</style>

// components/header/header.tsx
import NextLink from 'next/link'

import { HeaderLinks } from '@/components/header/header.links'
import { HeaderMobile } from '@/components/header/header.mobile'
import { Logo } from '@/components/logo'

export const Header = () => {
  return (
    <header className="sticky top-0 z-50 bg-background/40 backdrop-blur-sm">
      <div className="container flex h-16 items-center justify-between">
        <NextLink href="/" aria-label="Vinicius Vicentini, Back to homepage">
          <Logo />
        </NextLink>

        <nav className="flex items-center">
          <HeaderLinks className="hidden space-x-10 sm:flex" />

          <HeaderMobile className="sm:hidden" />
        </nav>
      </div>
    </header>
  )
}
