// components/Footer.vue
<template>
  <footer class="footer">
    <Container>
      <div class="footer-copyright">
        &copy; {{ new Date().getFullYear() }}

        <a
          class="link"
          href="https://www.linkedin.com/in/viniciushvc"
          target="_blank"
          rel="noreferrer noopener"
        >
          Vinicius Vicentini
        </a>

        <div class="footer-social">
          <a
            v-for="item in items"
            :key="item.name"
            :href="item.link"
            :title="item.name"
            target="_blank"
            rel="noreferrer noopener"
          >
            <component :is="`${item.name}-icon`" />
          </a>
        </div>
      </div>
    </Container>
  </footer>
</template>

<script>
import { TwitterIcon, GithubIcon, LinkedinIcon } from 'vue-feather-icons/'

export default {
  components: {
    Container: () => import('@/components/Container'),
    TwitterIcon,
    GithubIcon,
    LinkedinIcon,
  },

  data: () => ({
    items: [
      {
        name: 'Github',
        link: 'https://github.com/viniciushvc',
      },
      {
        name: 'Linkedin',
        link: 'https://www.linkedin.com/in/viniciushvc/',
      },
      {
        name: 'Twitter',
        link: 'https://twitter.com/ViniciusHVC',
      },
    ],
  }),
}
</script>

<style lang="scss" scoped>
.footer {
  padding: 50px 0;

  &-copyright {
    text-align: center;

    a {
      transition: var(--transition);

      &:hover {
        color: var(--colorPrimary);
      }

      svg {
        margin: 0 20px;
      }
    }
  }

  &-social {
    display: flex;
    justify-content: center;
    margin-top: 20px;
  }
}
</style>

// src/components/Footer.tsx
import { BsGithub, BsTwitter } from 'react-icons/bs'

import Box from '@primitives/Box'
import Grid from '@primitives/Grid'
import Text from '@primitives/Text'
import Stack from '@primitives/Stack'
import Link from '@primitives/Link'

import Container from '@components/Container'

const Footer = () => {
  return (
    <Box as="footer" css={{ py: '$5' }}>
      <Container>
        <Grid
          css={{
            columns: 'repeat(1, 1fr)',
            '@md': {
              columns: 'repeat(2, 1fr)',
            },
            justify: 'space-between',
            align: 'space-around',
            gap: '$3',
          }}
        >
          <Text
            css={{
              textAlign: 'center',
              '@md': {
                textAlign: 'left',
              },
            }}
          >
            All rights reserved &copy; Vinicius Vicentini 2021
          </Text>

          <Stack
            css={{
              justify: 'center',
              '@md': {
                justify: 'flex-end',
              },
              fontSize: '$2xl',
            }}
          >
            <Link
              href="https://github.com/viniciushvc"
              target="_blank"
              rel="noreferrer noopener"
              title="Visit my Github"
            >
              <BsGithub />
            </Link>

            <Link
              href="https://twitter.com/viniciushvc"
              target="_blank"
              rel="noreferrer noopener"
              title="Visit my Twitter"
            >
              <BsTwitter />
            </Link>
          </Stack>
        </Grid>
      </Container>
    </Box>
  )
}

export default Footer
